c
c     Input values 
c
      double precision  hgf,hale, hss,wm,zm !EW input parameters
      double precision  mtMS,mbMS,mcMS      !MSbar masses
      double precision  Vud,Vus             !CKM matrix elements
      integer  idef                         !EW couplings option
      common/input_values/hgf,hale,hss,wm,zm,
     &                    mtMS,mbMS,mcMS,
     &                    Vud,Vus, 
     &                    idef
